### ISSUE TITLE
module dependency?

### ISSUE THREAD

**Issue by jurgenweber** [ruxit/puppet#3]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type download at /etc/puppet/modules/ruxit_agent/manifests/init.pp:112 on node carzada-live-front-8a1a2a44.carzada.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

What is it?

**Comment by ruxit** [comment]
Hi.

did you install the install [http_download module](https://forge.puppetlabs.com/sledge/http_download)?
If not please install it with: `puppet module install sledge-http_download`
